// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Roa.Infrastructure.Context;

#nullable disable

namespace Roa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Roa.Domain.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DishTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DishTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PeriodId");

                    b.ToTable("Dish", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DishTypeId = 1,
                            Name = "Eggs",
                            PeriodId = 1
                        },
                        new
                        {
                            Id = 2,
                            DishTypeId = 1,
                            Name = "Steak",
                            PeriodId = 2
                        },
                        new
                        {
                            Id = 3,
                            DishTypeId = 2,
                            Name = "Toast",
                            PeriodId = 1
                        },
                        new
                        {
                            Id = 4,
                            DishTypeId = 2,
                            Name = "Potato",
                            PeriodId = 2
                        },
                        new
                        {
                            Id = 5,
                            DishTypeId = 3,
                            Name = "Coffee",
                            PeriodId = 1
                        },
                        new
                        {
                            Id = 6,
                            DishTypeId = 3,
                            Name = "Wine",
                            PeriodId = 2
                        },
                        new
                        {
                            Id = 7,
                            DishTypeId = 4,
                            Name = "Cake",
                            PeriodId = 2
                        });
                });

            modelBuilder.Entity("Roa.Domain.Entities.DishType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DishType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Entree"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Side"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drink"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dessert"
                        });
                });

            modelBuilder.Entity("Roa.Domain.Entities.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Period", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeSpan(0, 11, 59, 59, 0),
                            Name = "Morning",
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeSpan(0, 23, 59, 59, 0),
                            Name = "Night",
                            StartTime = new TimeSpan(0, 20, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("Roa.Domain.Entities.Dish", b =>
                {
                    b.HasOne("Roa.Domain.Entities.DishType", "DishType")
                        .WithMany("Dishes")
                        .HasForeignKey("DishTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Roa.Domain.Entities.Period", "Period")
                        .WithMany("Dishes")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DishType");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Roa.Domain.Entities.DishType", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("Roa.Domain.Entities.Period", b =>
                {
                    b.Navigation("Dishes");
                });
#pragma warning restore 612, 618
        }
    }
}
